### ISSUE TITLE
Install Ros

### ISSUE THREAD

**Issue by ShikherVerma** [AUV-IITK/rosauv#1]
preferable indigo distribution (http://wiki.ros.org/Distributions)

**Comment by arpit15** [comment]
Try to find out if the packages exist for ARM architecture. Otherwise you
won't be able to directly use code on odroid.

**Comment by ShikherVerma** [comment]
Ros is available for arm architectue

**Comment by ShikherVerma** [comment]
installed indigo-bare

**Comment by arpit15** [comment]
Problem is not with bare bones. Try all the packages and their dependencies
u would be using

**Comment by ShikherVerma** [comment]
ok
