### ISSUE TITLE
Test Wifi under water

### ISSUE THREAD

**Issue by ShikherVerma** [AUV-IITK/rosauv#24]
Step 1: find a friend with a water proof android
Step 2: convince him that you need to take his phone in water
Step 3: get punched in the face by your friend
Step 4: steal his phone
Step 5: install [connectBot]  (https://play.google.com/store/apps/details?id=org.connectbot&hl=en)
Step 6: run odroid inside water or Surround it with water from all sides. Probably use this
![panni](https://cloud.githubusercontent.com/assets/10194699/9547875/d55d5d30-4dba-11e5-9ee2-6a1be199c5fb.jpg)
Step 7: emerge the water proof phone in water and ssh

**Comment by agjayant** [comment]
We now have a 15m LAN cable..so forget wifi....
